// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace sistemaDB.Migrations
{
    [DbContext(typeof(ERPDBContext))]
    [Migration("20230516235920_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SistemaDB.Models.ClientContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ClientSystemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFinich")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataStart")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("ClientSystemId");

                    b.ToTable("TableClientContract");
                });

            modelBuilder.Entity("SistemaDB.Models.ClientSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TableClientSystem");
                });

            modelBuilder.Entity("SistemaDB.Models.ClientContract", b =>
                {
                    b.HasOne("SistemaDB.Models.ClientSystem", "ClientSystem")
                        .WithMany("ClientContracts")
                        .HasForeignKey("ClientSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientSystem");
                });

            modelBuilder.Entity("SistemaDB.Models.ClientSystem", b =>
                {
                    b.Navigation("ClientContracts");
                });
#pragma warning restore 612, 618
        }
    }
}
